### ISSUE TITLE
Connecting Pusher

### ISSUE THREAD

**Issue by trbsi** [pusher-community/pusher-websocket-swift#26]
We are building chat in our app. So we need Pusher only for chat. Since there are different scenarios like: losing internet connection, switching between conversations, turning app on and off... We had in mind to connect to Pusher only when user enters conversation (not inbox) and disconnect when he leaves conversation, to save connections.
Is that standard way to handle chat with Pusher?

**Comment by hamchapman** [comment]
(Same answer I gave in a, maybe your, support ticket :) )

People handle chat with Pusher in a variety of different ways. It really depends on what your requirements are and what your current setup is.

If, for example, you are saving all messages to a database and only using Pusher for the realtime component then I think, as you suggested, only subscribing to the relevant channel when you enter a chat (having fetched existing messages from your database) makes a lot of sense.

If, however, as another example, you're not persisting data then you'd want to me subscribed to Pusher for as much of the time as possible. Otherwise you'd need to implement some sort of check for when a user is "online" or not, in relation to Pusher (see here if you want more info: https://support.pusher.com/hc/en-us/articles/204113596-Showing-who-s-online-with-a-large-number-of-users​), and then when a user is offline you'd have to send a native push notification instead of a Pusher message. ​

As I said, it really depends on your use case above anything else.
